<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
    <name>ballbot_description</name>
    <version>0.0.0</version>
    <description>Ballbot Description Package</description>
    <maintainer email="atticusrussell@gmail.com">Atticus Russell</maintainer>
    <license>Apache 2.0</license>
    <url type="repository">https://github.com/atticusrussell/ballbot</url>
    <url type="bugtracker">https://github.com/atticusrussell/ballbot/issues</url>
    <buildtool_depend>ament_cmake</buildtool_depend>
    <exec_depend>joint_state_publisher</exec_depend>
    <exec_depend>robot_state_publisher</exec_depend>
    <exec_depend>xacro</exec_depend>
    <!-- for gazebo plugins -->
    <export>
        <build_type>ament_cmake</build_type>
        <gazebo_ros gazebo_model_path="${prefix}/share"/>
    </export>
</package>
