<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:macro name="base" params="length width height mass wheel_radius wheel_pos_z">
    <link name="base_footprint"/>
    
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 1.57"/>
        <geometry>
          <!-- <box size="${length} ${width} ${height}"/> -->
          <mesh filename="file://$(find catbot_description)/meshes/visual/still_chassis_assm_visual.stl"/>
        </geometry>
        <material name="still_chassis_assm_material">
        <color rgba="0.66987717125153911635 0.81712318213796708566 0.66602980483018847657 1.0" />
      </material>
      </visual>
      
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${length} ${width} ${height}"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="${mass}"/>
        <inertia ixx="${(1/12) * mass * ((width  * width)  + (height * height))}" ixy="0.0" ixz="0.0"
                 iyy="${(1/12) * mass * ((length * length) + (height * height))}" iyz="0.0"
                 izz="${(1/12) * mass * ((length * length) + (width  * width))}"/>
      </inertial>
    </link>

    <gazebo reference="base_link">  
      <material>Gazebo/Green</material>
    </gazebo>

    <joint name="base_to_footprint" type="fixed">
      <parent link="base_footprint"/>
      <child link="base_link"/>
      <origin xyz="0 0 ${wheel_radius - wheel_pos_z}" rpy="0 0 0"/>
    </joint>
  </xacro:macro>
</robot>
