<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <!-- Specify some standard inertial calculations https://en.wikipedia.org/wiki/List_of_moments_of_inertia -->
    <!-- These make use of xacro's mathematical functionality -->

    <xacro:macro name="inertial_sphere" params="mass radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(2/5) * mass * (radius*radius)}" ixy="0.0" ixz="0.0"
                    iyy="${(2/5) * mass * (radius*radius)}" iyz="0.0"
                    izz="${(2/5) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>  


    <xacro:macro name="inertial_box" params="mass x y z *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (y*y+z*z)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (x*x+z*z)}" iyz="0.0"
                    izz="${(1/12) * mass * (x*x+y*y)}" />
        </inertial>
    </xacro:macro>


    <xacro:macro name="inertial_cylinder" params="mass length radius *origin">
        <inertial>
            <xacro:insert_block name="origin"/>
            <mass value="${mass}" />
            <inertia ixx="${(1/12) * mass * (3*radius*radius + length*length)}" ixy="0.0" ixz="0.0"
                    iyy="${(1/12) * mass * (3*radius*radius + length*length)}" iyz="0.0"
                    izz="${(1/2) * mass * (radius*radius)}" />
        </inertial>
    </xacro:macro>

    <!-- inertial calculations handy for catbot -->

    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
    <xacro:property name="wheel_mass" value="0.05"/>

    <xacro:property name="wheel_assm_mass" value="0.055"/>

    <xacro:macro name="wheel_inertia">
        <xacro:inertial_cylinder mass="${wheel_assm_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 -0.006" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>

    <xacro:property name="chassis_mass" value="1.015668141636539179"/>
    <xacro:property name="chassis_length" value="0.242"/>
    <xacro:property name="chassis_width" value="0.120"/>
    <xacro:property name="chassis_height" value="0.105"/>

    <xacro:macro name="chassis_inertia">
        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="${chassis_length/2} 0 ${chassis_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </xacro:macro>

    <xacro:macro name="wheel_cylinder_collision">
        <geometry>
            <cylinder length="${wheel_thickness}" radius="${wheel_radius}"/>
        </geometry>
    </xacro:macro>
</robot>
