name: ROS Lint

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  general_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [lint_cmake, xmllint]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          package-name:
            catbot_description

  python_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [flake8, pep257]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          package-name:
            catbot_description

  cpp_lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify]
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@master
      - uses: ros-tooling/action-ros-lint@master
        with:
          linter: ${{ matrix.linter }}
          package-name:
            
