name: ROS

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Test
        uses: ./.github/actions/test/

  lint:
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Check for C/C++ files
        id: check_files
        run: echo "::set-output name=cpp_files_present::$(find . -name '*.c' -o -name '*.cpp' | wc -l)"
      -
        name: Run C/C++ linter
        if: contains(matrix.linter, 'cppcheck') || contains(matrix.linter, 'cpplint') || contains(matrix.linter, 'uncrustify') && steps.check_files.outputs.cpp_files_present > '0'
        uses: ./.github/actions/lint/
        env:
          LINTER: ${{ matrix.linter }}
      -
        name: Run other linters
        if:  ! contains(matrix.linter, 'cppcheck' || 'cpplint' || 'uncrustify')
        uses: ./.github/actions/lint/
        env:
          LINTER: ${{ matrix.linter }}
